language: python
python:
- '2.7'
- '3.6'
install:
- pip install -r requirements.txt
- python setup.py install
script:
- py.test
deploy:
  provider: pypi
  user:
    secure: umTIpHcz10Topf1ZdfUk21boj1TI7TGCPgvrXtbFJ8AtyaH/I2ktP3ZHJLmUDK7jz5V/lXgzZO9WPSn84/wZudZdgu3L6es+zBYvNy6LG9mc9XdMVaEnEx2PYP+jWcBy3PXzcRPKZahJ2F73/qZsbaY50TPi++Zcfv8bSvwxdw83fb8NpRb+vhDIGnd8XgA9DdTtH/Y6udsk8K3g0h/OIekUYSZHo+jODUR5h3vtggbbT+FMbpQsncOWhEy6km1U2U2Nm6zC3L2xXxKrpwJz23tmR9qmmLXG53ojFoBzxR/CjnAXGxVaKxNz8NsZ7NXiOklFOBmK27IWCsuQ9E0fNiwSV35wexBSsc+KaWQ4jw5CMrV7dDR4cRqr7toEDqY/SxI5PYM0LVQvfqtJOh5WNPlQTIJHF4TcHgLjowwR0j1BHvcYP7q4mL6fCcx6etCa9h5LJmZy924OAfOw2OXfed/3kBiQn/p01/+myZG2oMtA/5XBFC+PONFr1+hVhFfb9GD5GSjn+BBHBINd5LzGELdSeGgxKGaMuNUCWz7JY/zDuzxvKQL9vXfScXmnqtivTabzkzGISUJPRlTupqT9PA2RH6i3zVK0XYCjPJ78NMWOYLKfPhICNxiDVzwSfqKJrSCheuVSFwbpdLJ/glEIjHCB7JUG5H0WnYC03NHgUyw=
  password:
    secure: lQ5dDsj2p44jhgSNLSA+S8uw78TNCsqsraghqb5WHpcjmj0Kg5skUw8Zwa4fAto0ReniAxDMjIJgNPLzTDnN0/qCt/yc/CizwQR7Yl8/rMbI3Sk+MxHpJ/siQpTzhtm0IuFjoYhzTURlcvMtFhqD91/2DQqiyiTx5pjceCKwctpx93EzKZBa3SOzxr9JxlOzicHFWOQG9ZdZWZMaszgXi7IrIcgBaYXnxwsD2RRcm61Adcw3ZKixLqTA2qR9jhi62a1n5GhZl8qBNxZSTa72IRmLab/zHDiXrretuxmgVcN2yjgM3YGggtsV1ZnR1+BSNx0Emt5WENFPwZ6o+xxDVFQm1z997efQSFCsTvm8VCjM7+jzPeOUGeJEuRW7NXh2LtKis2dfUIqzWw8QfVp+6+YCHQhfCZfgbVHdb6+/151lZMxlSmeoLZjDmaRvl46iFnFv6U/ySjHvIZ87MP/76AiXB6AQnWHQd8/HBC+/1e69xf9iIflvCIhti1eCj5keyFspFFhJ1X6sHdplty30JcrRnyEtNOKk3j2FqXUe/G5I7qV7oLaCJTnB9LzEAFJViq/b+mhgwdY5dYwX9qoBtWVzBT+g6yKaPcpIr5SBS6mDODkxNlAzTDCgAK4P9YMp6opNNUqak+F3o06JhYWOpET+jP3jmPd34w+oSCwvahs=
  on:
    branch: master
    python: '3.6'
    tags: true